// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CS_Padron_Importador.Models;

public partial class Circuito
{
    public short IdCircuito { get; set; }

    public byte IdDistrito { get; set; }

    public byte IdSeccion { get; set; }

    public short CodigoNumero { get; set; }

    public string CodigoLetra { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Persona> Persona { get; set; } = new List<Persona>();

    public virtual Seccion Seccion { get; set; }
}