// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CS_Padron_Importador.Models;

public partial class Distrito
{
    public byte IdDistrito { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Seccion> Seccion { get; set; } = new List<Seccion>();
}