// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CS_Padron_Importador.Models;

public partial class Persona
{
    public int IdPersona { get; set; }

    public string Apellido { get; set; }

    public string Nombre { get; set; }

    public byte IdDocumentoTipo { get; set; }

    public int DocumentoNumero { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public string Genero { get; set; }

    public string Domicilio { get; set; }

    public string Localidad { get; set; }

    public short? CodigoPostal { get; set; }

    public byte IdNacionalidadTipo { get; set; }

    public byte IdDistrito { get; set; }

    public byte IdSeccion { get; set; }

    public byte IdCircuito { get; set; }

    public virtual Circuito Circuito { get; set; }

    public virtual DocumentoTipo IdDocumentoTipoNavigation { get; set; }

    public virtual NacionalidadTipo IdNacionalidadTipoNavigation { get; set; }
}