// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CS_Padron_Importador.Models;

public partial class Seccion
{
    public byte IdDistrito { get; set; }

    public byte IdSeccion { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Circuito> Circuito { get; set; } = new List<Circuito>();

    public virtual Distrito IdDistritoNavigation { get; set; }
}